// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: notifyMe/notifyMe.proto

package notifyMe

import (
	fmt "fmt"
	common "github.com/cargod-bj/b2c-proto-common/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for NotifyMe service

func NewNotifyMeEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for NotifyMe service

type NotifyMeService interface {
	//新增 notifyMe
	Add(ctx context.Context, in *NotifyMeDTO, opts ...client.CallOption) (*common.Response, error)
}

type notifyMeService struct {
	c    client.Client
	name string
}

func NewNotifyMeService(name string, c client.Client) NotifyMeService {
	return &notifyMeService{
		c:    c,
		name: name,
	}
}

func (c *notifyMeService) Add(ctx context.Context, in *NotifyMeDTO, opts ...client.CallOption) (*common.Response, error) {
	req := c.c.NewRequest(c.name, "NotifyMe.Add", in)
	out := new(common.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for NotifyMe service

type NotifyMeHandler interface {
	//新增 notifyMe
	Add(context.Context, *NotifyMeDTO, *common.Response) error
}

func RegisterNotifyMeHandler(s server.Server, hdlr NotifyMeHandler, opts ...server.HandlerOption) error {
	type notifyMe interface {
		Add(ctx context.Context, in *NotifyMeDTO, out *common.Response) error
	}
	type NotifyMe struct {
		notifyMe
	}
	h := &notifyMeHandler{hdlr}
	return s.Handle(s.NewHandler(&NotifyMe{h}, opts...))
}

type notifyMeHandler struct {
	NotifyMeHandler
}

func (h *notifyMeHandler) Add(ctx context.Context, in *NotifyMeDTO, out *common.Response) error {
	return h.NotifyMeHandler.Add(ctx, in, out)
}
