// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: login/login.proto

package login

import (
	fmt "fmt"
	common "github.com/cargod-bj/b2c-proto-common/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Login service

func NewLoginEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Login service

type LoginService interface {
	//通过手机号发送短信，返回data.nil
	SendSMS(ctx context.Context, in *LoginDTO, opts ...client.CallOption) (*common.Response, error)
	//用户登录校验，返回token
	Login(ctx context.Context, in *LoginDTO, opts ...client.CallOption) (*common.Response, error)
}

type loginService struct {
	c    client.Client
	name string
}

func NewLoginService(name string, c client.Client) LoginService {
	return &loginService{
		c:    c,
		name: name,
	}
}

func (c *loginService) SendSMS(ctx context.Context, in *LoginDTO, opts ...client.CallOption) (*common.Response, error) {
	req := c.c.NewRequest(c.name, "Login.SendSMS", in)
	out := new(common.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loginService) Login(ctx context.Context, in *LoginDTO, opts ...client.CallOption) (*common.Response, error) {
	req := c.c.NewRequest(c.name, "Login.Login", in)
	out := new(common.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Login service

type LoginHandler interface {
	//通过手机号发送短信，返回data.nil
	SendSMS(context.Context, *LoginDTO, *common.Response) error
	//用户登录校验，返回token
	Login(context.Context, *LoginDTO, *common.Response) error
}

func RegisterLoginHandler(s server.Server, hdlr LoginHandler, opts ...server.HandlerOption) error {
	type login interface {
		SendSMS(ctx context.Context, in *LoginDTO, out *common.Response) error
		Login(ctx context.Context, in *LoginDTO, out *common.Response) error
	}
	type Login struct {
		login
	}
	h := &loginHandler{hdlr}
	return s.Handle(s.NewHandler(&Login{h}, opts...))
}

type loginHandler struct {
	LoginHandler
}

func (h *loginHandler) SendSMS(ctx context.Context, in *LoginDTO, out *common.Response) error {
	return h.LoginHandler.SendSMS(ctx, in, out)
}

func (h *loginHandler) Login(ctx context.Context, in *LoginDTO, out *common.Response) error {
	return h.LoginHandler.Login(ctx, in, out)
}
