// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: favorite/favorite.proto

package favorite

import (
	fmt "fmt"
	common "github.com/cargod-bj/b2c-proto-common/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Favorite service

func NewFavoriteEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Favorite service

type FavoriteService interface {
	//新增客户，返回data.nil
	Add(ctx context.Context, in *FavoriteDTO, opts ...client.CallOption) (*common.Response, error)
	//删除客户，这里是假删除，设置status为1表示已删除，返回data.nil
	Delete(ctx context.Context, in *DeleteId, opts ...client.CallOption) (*common.Response, error)
	//更新客户，返回data.nil
	Update(ctx context.Context, in *FavoriteDTO, opts ...client.CallOption) (*common.Response, error)
	//获取客户列表，返回客户列表
	GetList(ctx context.Context, in *common.Page, opts ...client.CallOption) (*common.Response, error)
	//获取收藏的车辆iDs
	GetByUser(ctx context.Context, in *User, opts ...client.CallOption) (*common.Response, error)
	//删除收藏
	DeleteFavorite(ctx context.Context, in *DelFavorite, opts ...client.CallOption) (*common.Response, error)
}

type favoriteService struct {
	c    client.Client
	name string
}

func NewFavoriteService(name string, c client.Client) FavoriteService {
	return &favoriteService{
		c:    c,
		name: name,
	}
}

func (c *favoriteService) Add(ctx context.Context, in *FavoriteDTO, opts ...client.CallOption) (*common.Response, error) {
	req := c.c.NewRequest(c.name, "Favorite.Add", in)
	out := new(common.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *favoriteService) Delete(ctx context.Context, in *DeleteId, opts ...client.CallOption) (*common.Response, error) {
	req := c.c.NewRequest(c.name, "Favorite.Delete", in)
	out := new(common.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *favoriteService) Update(ctx context.Context, in *FavoriteDTO, opts ...client.CallOption) (*common.Response, error) {
	req := c.c.NewRequest(c.name, "Favorite.Update", in)
	out := new(common.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *favoriteService) GetList(ctx context.Context, in *common.Page, opts ...client.CallOption) (*common.Response, error) {
	req := c.c.NewRequest(c.name, "Favorite.GetList", in)
	out := new(common.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *favoriteService) GetByUser(ctx context.Context, in *User, opts ...client.CallOption) (*common.Response, error) {
	req := c.c.NewRequest(c.name, "Favorite.GetByUser", in)
	out := new(common.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *favoriteService) DeleteFavorite(ctx context.Context, in *DelFavorite, opts ...client.CallOption) (*common.Response, error) {
	req := c.c.NewRequest(c.name, "Favorite.DeleteFavorite", in)
	out := new(common.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Favorite service

type FavoriteHandler interface {
	//新增客户，返回data.nil
	Add(context.Context, *FavoriteDTO, *common.Response) error
	//删除客户，这里是假删除，设置status为1表示已删除，返回data.nil
	Delete(context.Context, *DeleteId, *common.Response) error
	//更新客户，返回data.nil
	Update(context.Context, *FavoriteDTO, *common.Response) error
	//获取客户列表，返回客户列表
	GetList(context.Context, *common.Page, *common.Response) error
	//获取收藏的车辆iDs
	GetByUser(context.Context, *User, *common.Response) error
	//删除收藏
	DeleteFavorite(context.Context, *DelFavorite, *common.Response) error
}

func RegisterFavoriteHandler(s server.Server, hdlr FavoriteHandler, opts ...server.HandlerOption) error {
	type favorite interface {
		Add(ctx context.Context, in *FavoriteDTO, out *common.Response) error
		Delete(ctx context.Context, in *DeleteId, out *common.Response) error
		Update(ctx context.Context, in *FavoriteDTO, out *common.Response) error
		GetList(ctx context.Context, in *common.Page, out *common.Response) error
		GetByUser(ctx context.Context, in *User, out *common.Response) error
		DeleteFavorite(ctx context.Context, in *DelFavorite, out *common.Response) error
	}
	type Favorite struct {
		favorite
	}
	h := &favoriteHandler{hdlr}
	return s.Handle(s.NewHandler(&Favorite{h}, opts...))
}

type favoriteHandler struct {
	FavoriteHandler
}

func (h *favoriteHandler) Add(ctx context.Context, in *FavoriteDTO, out *common.Response) error {
	return h.FavoriteHandler.Add(ctx, in, out)
}

func (h *favoriteHandler) Delete(ctx context.Context, in *DeleteId, out *common.Response) error {
	return h.FavoriteHandler.Delete(ctx, in, out)
}

func (h *favoriteHandler) Update(ctx context.Context, in *FavoriteDTO, out *common.Response) error {
	return h.FavoriteHandler.Update(ctx, in, out)
}

func (h *favoriteHandler) GetList(ctx context.Context, in *common.Page, out *common.Response) error {
	return h.FavoriteHandler.GetList(ctx, in, out)
}

func (h *favoriteHandler) GetByUser(ctx context.Context, in *User, out *common.Response) error {
	return h.FavoriteHandler.GetByUser(ctx, in, out)
}

func (h *favoriteHandler) DeleteFavorite(ctx context.Context, in *DelFavorite, out *common.Response) error {
	return h.FavoriteHandler.DeleteFavorite(ctx, in, out)
}
